public class ConfictClass{

//addedd comment by Dev1

//addedd comment by Dev1

//addedd comment1 by Dev1


////addedd comment2 by Dev1

//addedd comment by Dev1

//addedd comment1 by Dev1


////addedd comment2 by Dev1


////addedd comment2 by Dev1


//addedd comment1 by Dev2


////addedd comment2 by Dev2


////addedd comment2 by Dev2

//addedd comment by Dev1

//addedd comment1 by Dev1


////addedd comment2 by Dev1
}